"use client";
import {useEffect,useState} from "react";
type Step="home"|"privacy"|"safety"|"quiz"|"reveal"|"waiting"|"lee"|"map"|"help";type A={q:string;a:string};
const qs=[
["When would this conversation feel most manageable?","Today","In the next few days","Next week","I’m not sure yet"],
["How much uninterrupted time could you realistically have?","10 minutes","20–30 minutes","About an hour","Time is hard to predict"],
["Which pace would help you stay grounded?","Brief and direct","Slow with pauses","One topic at a time","Let the other person lead"],
["When do you usually feel clearest?","Morning","Afternoon","Evening","It varies"],
["What kind of opening feels most natural?","Say the main point first","Start with context","Ask if it’s a good time","Name that this is difficult"],
["If things feel intense, what pause would work best?","A quiet minute","A short walk","Continue another day","Have a support person nearby"]];
export default function Page(){const[s,setS]=useState<Step>("home"),[i,setI]=useState(0),[as,setAs]=useState<A[]>([]);useEffect(()=>{document.querySelector<HTMLElement>("section h1")?.focus()},[s,i]);const exit=()=>{sessionStorage.clear();location.replace("https://www.google.com/")},reset=()=>{sessionStorage.clear();setS("home");setI(0);setAs([])},pick=(a:string)=>{setAs([...as,{q:qs[i][0],a}]);i===5?setS("reveal"):setI(i+1)};return <main><header>{s==="help"?<span className="brand" aria-label="NextChapter">NextChapter<span>.</span></span>:{s==="help"?<span className="brand" aria-label="NextChapter">NextChapter<span>.</span></span>:<button className="brand" onClick={reset}>NextChapter<span>.</span></button>}}<button className="exit" onClick={exit}>Quick Exit</button></header>{s!=="home"&&s!=="help"&&<div className="progress"><i style={{width:`${s==="quiz"?25+(i+1)*6:({privacy:10,safety:20,reveal:65,waiting:75,lee:88,map:100}[s]||5)}%`}}/><small>{s==="quiz"?`Question ${i+1} of 6`:"Private demo · a few calm steps"}</small></div>}<p className="sr" role="status" aria-live="polite">{s==="quiz"?`Question ${i+1} of 6`:stepLabel(s)}</p><section className={s}>
{s==="home"&&<Box eyebrow="A steadier way forward" title="Prepare for a conversation that matters." text="NextChapter helps you find the right time, pace, and words—privately, and one small choice at a time."><Go onClick={()=>setS("privacy")}>Try the guided demo →</Go><p className="micro">About 3 minutes · No account · No typing</p><div className="cols">{[["01","Choose your rhythm","Six simple choices shape a manageable approach."],["02","See what you chose","Review your exact selections before moving on."],["03","Leave with a map","A clear, gentle structure for what comes next."]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div></Box>}
{s==="privacy"&&<Box eyebrow="Before we begin" title="Your choices stay in this tab." text="This demo sends nothing anywhere. Your choices stay only in this page’s memory and disappear if you reload or close the tab."><aside><strong>You stay in control.</strong><p>Quick Exit clears the demo and leaves immediately.</p></aside><Go onClick={()=>setS("safety")}>I understand</Go></Box>}
{s==="safety"&&<Box eyebrow="A quick safety check" title="Are you in immediate danger, or worried this conversation could put you at risk?" text="Your wellbeing comes first. This demo is only for conversations that feel safe to prepare for."><div className="choices"><button onClick={()=>safetyChoice("safe",setS)}>No, I feel safe to continue <span>→</span></button><button onClick={()=>safetyChoice("support",setS)}>I need support right now <span>→</span></button></div></Box>}
{s==="quiz"&&<Box eyebrow={`Time & rhythm · ${i+1} of 6`} title={qs[i][0]} text="Choose what feels closest. There are no right answers."><Choices items={qs[i].slice(1)} fn={pick}/></Box>}
{s==="reveal"&&<Box eyebrow="Your exact choices" title="Here’s what you told us." text="No score and no interpretation—just your selections, exactly as you made them."><div className="answers">{as.map((x,j)=><article key={x.q}><b>{String(j+1).padStart(2,"0")}</b><div><small>{x.q}</small><strong>{x.a}</strong></div></article>)}</div><Go onClick={()=>setS("waiting")}>Continue with this preview</Go></Box>}
{s==="waiting"&&<Box eyebrow="A quiet moment" title="Your choices can become a simple conversation plan." text="In the full experience, you could pause here and return when ready. For this demo, we’ll show a guided handoff."><div className="orb" aria-hidden="true"/><Go onClick={()=>setS("lee")}>Meet Lee, your demo guide</Go></Box>}
{s==="lee"&&<Box eyebrow="Demo guide · fixed walkthrough" title="Lee keeps it practical." text="Lee is a preset demo—not a live person or AI. Three ideas turn your choices into a calm opening."><div className="cols">{[["01","Set the container","Choose a time and name how long you have."],["02","Open gently","Begin in the style you selected."],["03","Protect the pause","Agree on what happens if someone needs space."]].map(x=><article key={x[0]}><b>{x[0]}</b><h2>{x[1]}</h2><p>{x[2]}</p></article>)}</div><blockquote>“You don’t need perfect words. You only need a clear first step.”</blockquote><Go onClick={()=>setS("map")}>Build my conversation map</Go></Box>}
{s==="map"&&<Box eyebrow="Your conversation map" title="A small plan for a meaningful start." text="Use this as a reminder, not a script. You can change your mind at any point."><div className="maplist">{[["Make room",`${as[0]?.a} · ${as[1]?.a}`],["Set the pace",`${as[2]?.a} · ${as[3]?.a}`],["Begin",as[4]?.a],["Keep an exit open",as[5]?.a]].map((x,j)=><article key={x[0]}><b>{j+1}</b><div><small>{x[0]}</small><h2>{x[1]}</h2></div></article>)}</div><div className="buttons"><Go onClick={reset}>Start again</Go><button className="secondary" onClick={()=>print()}>Print this map</button></div><p className="micro">Nothing has been sent or saved to an account.</p></Box>}
{s==="help"&&<Box eyebrow="Your safety comes first" title="Please don’t continue with this conversation right now." text="If you may be in immediate danger, contact local emergency services. If safe, move somewhere secure and contact someone you trust."><div className="resources"><a href="tel:911"><strong>Call emergency services</strong><small>In the U.S., call 911</small></a><a href="tel:988"><strong>Call or text 988</strong><small>U.S. Suicide & Crisis Lifeline</small></a><a href="https://www.thehotline.org/" target="_blank" rel="noreferrer noopener"><strong>Domestic Violence Hotline ↗</strong><small>Confidential safety planning</small></a><a href="https://findahelpline.com/" target="_blank" rel="noreferrer noopener"><strong>Find support outside the U.S. ↗</strong><small>Helplines by country</small></a></div></Box>}
</section><footer>Preparation tool only — not emergency or professional care.</footer></main>}
function Box({eyebrow,title,text,children}:{eyebrow:string,title:string,text:string,children:React.ReactNode}){return <div className="box"><p className="eyebrow">{eyebrow}</p><h1 tabIndex={-1}>{title}</h1><p className="lede">{text}</p>{children}</div>};function Go(p:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...p} className="primary"/>};function Choices({items,fn}:{items:string[];fn:(x:string)=>void}){return <div className="choices">{items.map(x=><button onClick={()=>fn(x)} key={x}>{x}<span>→</span></button>)}</div>}

function safetyChoice(value:"safe"|"support",set:(s:Step)=>void){set(value==="safe"?"quiz":"help")}function stepLabel(s:Step){return ({home:"Welcome",privacy:"Privacy information",safety:"Safety check",quiz:"Time and rhythm",reveal:"Your exact choices",waiting:"A quiet moment",lee:"Demo guide",map:"Your conversation map",help:"Immediate support resources"} as const)[s]}

function safetyChoice(value:"safe"|"support",set:(s:Step)=>void){set(value==="safe"?"quiz":"help")}function stepLabel(s:Step){return ({home:"Welcome",privacy:"Privacy information",safety:"Safety check",quiz:"Time and rhythm",reveal:"Your exact choices",waiting:"A quiet moment",lee:"Demo guide",map:"Your conversation map",help:"Immediate support resources"} as const)[s]}
